# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
#
# jupyterLab_hdf : HDF5 api for Jupyter/Jupyterlab

openapi: 3.0.0
info:
  title: JupyterLab HDF5 proxy
  description: "Proxies HDF5 API requests from JupyterLab to HDF5."
  version: 0.3.0

paths:
  /hdf/contents/{fpath}{?uri}:
    get:
      summary: "Get the contents of the hdf object pointed to by the uri in the file at fpath."
      parameters:
        - $ref: '#/components/parameters/fpath'
        - $ref: '#/components/parameters/uri'
      responses:
        '200':
          $ref: '#/components/responses/hobjs'
        '400':
          description: The request was malformed; url should be of the format "fpath?uri=uri"
        '401':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that does not exist.
        '500':
          description: Found and opened file, error getting contents from object specified by the uri.

    post:
      summary: "Get slices of data from the hdf dataset pointed to by the uri in the file at fpath."
      parameters:
        - $ref: '#/components/parameters/fpath'
        - $ref: '#/components/parameters/uri'
      requestBody:
        $ref: '#/components/requestBodies/slices'
      responses:
        '200':
          $ref: '#/components/responses/dataslab'
        '400':
          description: The request was malformed; url should be of the format "fpath?uri=uri"
        '401':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that does not exist.
        '500':
          description: Found and opened file, error getting data from dataset specified by the uri.

components:
  parameters:
    fpath:
      name: fpath
      in: path
      required: true
      description: "Path on disk to an HDF5 file."
      schema:
        type: string
        format: uri
    uri:
      name: uri
      in: query
      required: true
      description: "Path within an HDF5 file to a specific group or dataset."
      schema:
        type: string

  requestBodies:
    slices:
      description: "list of slices"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/slice'

  responses:
    hobjs:
      description: "list of hdf5 objects"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/hobj'
    dataslab:
      description: "slab of hdf5 dataset represented as list-of-list-of-number (always 2D)"
      content:
        application/json:
          schema:
            type: array
            items:
              type: array
              items:
                type: number

  schemas:
    hobj:
      description: "data representing an arbitrary hdf5 object"
      type: object
      properties:
        type:
          description: "only `group` or `dataset` (for now)"
          type: string
        name:
          description: "object name"
          type: string
        uri:
          description: "full uri pointing to the object"
          type: string
    slice:
      description: "a slice. Up to 3 integers, same syntax as for Python `slice` built-in"
      type: array
      items:
        type: integer
      nullable: true
      maxItems: 3
