# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
#
# jupyterLab_hdf : HDF5 api for Jupyter/Jupyterlab

openapi: 3.0.0
info:
  title: JupyterLab HDF5 proxy
  description: "Proxies HDF5 API requests from JupyterLab to HDF5."
  version: 0.6.0


paths:
  /hdf/attrs/{fpath}{?uri}:
    parameters:
      - $ref: "#/components/parameters/fpath"
      - $ref: "#/components/parameters/uri"

    get:
      description: "get the attributes of an hdf object"
      summary: "get the attributes of an hdf object"
      responses:
        "200":
          $ref: "#/components/responses/attrs"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"

  /hdf/contents/{fpath}{?uri}{?ixstr}{?min_ndim}:
    parameters:
      - $ref: "#/components/parameters/fpath"
      - $ref: "#/components/parameters/uri"
      - $ref: "#/components/parameters/ixstr"
      - $ref: "#/components/parameters/min_ndim"

    get:
      description: "get the contents of an hdf object"
      summary: "get the contents of an hdf object"
      responses:
        "200":
          $ref: "#/components/responses/contents"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"

  /hdf/data/{fpath}{?uri}{?ixstr}{?subixstr}{?min_ndim}:
    parameters:
      - $ref: "#/components/parameters/fpath"
      - $ref: "#/components/parameters/uri"
      - $ref: "#/components/parameters/ixstr"
      - $ref: "#/components/parameters/subixstr"
      - $ref: "#/components/parameters/min_ndim"

    get:
      description: "get raw array data from one hdf dataset, as a json blob"
      summary: "get data from an hdf dataset"
      responses:
        "200":
          $ref: "#/components/responses/data"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"

  /hdf/meta/{fpath}{?uri}{?ixstr}{?min_ndim}:
    parameters:
      - $ref: "#/components/parameters/fpath"
      - $ref: "#/components/parameters/uri"
      - $ref: "#/components/parameters/ixstr"
      - $ref: "#/components/parameters/min_ndim"

    get:
      description: "get the metadata of an hdf object. If the object is a dataset and the ixstr parameter is provided, all shape-related metadata will be for the slab specified by ixstr"
      summary: "get the metadata of an hdf object"
      responses:
        "200":
          $ref: "#/components/responses/meta"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"

  /hdf/snippet/{fpath}{?uri}:
    parameters:
      - $ref: "#/components/parameters/fpath"
      - $ref: "#/components/parameters/uri"
    get:
      description: "get a Python snippet that fetches the hdf dataset or group pointed to by the path and uri"
      summary: "get a Python snippet that fetches an hdf dataset or group"
      responses:
        "200":
          $ref: "#/components/responses/py_snippet"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"


components:
  parameters:
    fpath:
      name: fpath
      in: path
      required: true
      description: "path on disk to an HDF5 file"
      schema:
        type: string
        format: uri
    ixstr:
      name: ixstr
      in: query
      required: false
      description: "index specifying which ND slab of a dataset to consider when fetching data. Uses numpy-style index syntax"
      schema:
        type: string
    subixstr:
      name: subixstr
      in: query
      required: false
      description: "index specifying which chunk (of the ND slab specified by ixstr) of a dataset to fetch. Uses numpy-style index syntax. The count of slices in ixstr and subixstr should match"
      schema:
        type: string
    min_ndim:
      name: min_ndim
      in: query
      required: false
      description: "if set, all shape-related metadata and array data fetched from a dataset will be promoted to have at least this many dimensions"
      schema:
        type: number
    uri:
      name: uri
      in: query
      required: true
      description: "path within an HDF5 file to a specific group or dataset"
      schema:
        type: string

  responses:
    "400":
      description: "the request was malformed; url should be of the format 'fpath?uri=uri'"
    "401":
      description: "the request did not specify a file that `h5py` could understand"
    "403":
      description: "the request specified a file that does not exist"
    "500":
      description: "found and opened file, error getting contents from object specified by the uri"
    attrs:
      description: "attributes of an arbitrary hdf object, as a dictionary"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/attrs"
    contents:
      description: "data representing an arbitrary hdf object, in the format required by the jupyterlab `Contents` stack. May be either a single object or an array"
      content:
        application/json:
          schema:
            oneOf:
            - $ref: "#/components/schemas/contents"
            - type: array
              items:
                $ref: "#/components/schemas/contents"
    data:
      description: "a chunk of raw array data from an hdf dataset. May be of any dimensionality"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/data"
    meta:
      description: "metadata of an arbitrary hdf object, as a dictionary"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/meta"
    py_snippet:
      description: "python code snippet"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/py_snippet"

  schemas:
    attrs:
      description: "attributes of an arbitrary hdf object, as a dictionary"
      type: object
      additionalProperties: true
    dataset_contents:
      description: "a basic description of an hdf dataset, in the format required by the jupyterlab `Contents` stack"
      required: [name, type, uri]
      type: object
      properties:
        content:
          $ref: "#/components/schemas/dataset_meta"
        name:
          description: "object name (ie last part of uri)"
          type: string
        type:
          description: "the string literal 'dataset'"
          enum: ["dataset"]
          type: string
        uri:
          description: "full uri pointing to the object"
          type: string
    group_contents:
      description: "a basic description of an hdf group, in the format required by the jupyterlab `Contents` stack"
      required: [name, type, uri]
      type: object
      properties:
        content:
          $ref: "#/components/schemas/group_meta"
        name:
          description: "object name (ie last part of uri)"
          type: string
        type:
          description: "the string literal 'group'"
          enum: ["group"]
          type: string
        uri:
          description: "full uri pointing to the object"
          type: string
    contents:
      description: "data representing an arbitrary hdf object, in the format required by the jupyterlab `Contents` stack"
      discriminator:
        propertyName: type
        mapping:
          dataset: "#/components/schemas/dataset_contents"
          group: "#/components/schemas/group_contents"
      oneOf:
        - $ref: "#/components/schemas/dataset_contents"
        - $ref: "#/components/schemas/group_contents"
    data:
      description: "a chunk of raw array data from an hdf dataset. May be of any dimensionality"
      type: array
      items:
        oneOf:
          - type: number
          - $ref: "#/components/schemas/data"
    dataset_meta:
      description: "metadata of an hdf dataset, as a dictionary"
      required: [dtype, labels, name, ndim, shape, size, type]
      type: object
      properties:
        dtype:
          description: "datatype of an hdf dataset"
          type: string
        labels:
          description: "ranges that label the indices of an hdf dataset, given as an array of slices"
          type: array
          items:
            $ref: "#/components/schemas/slice"
        name:
          description: "name of hdf dataset"
          type: string
        ndim:
          description: "count of dimensions of an hdf dataset"
          type: number
        shape:
          description: "shape of an hdf dataset"
          type: array
          items:
            type: number
        size:
          description: "count of entries of an hdf dataset"
          type: number
        type:
          description: "the string literal 'dataset'"
          enum: ["dataset"]
          type: string
    group_meta:
      description: "metadata of an hdf group, as a dictionary"
      required: [name, type]
      type: object
      properties:
        name:
          description: "name of hdf group"
          type: string
        type:
          description: "the string literal 'group'"
          enum: ["group"]
          type: string
    meta:
      description: "the metadata of an hdf object"
      discriminator:
        propertyName: type
        mapping:
          dataset: "#/components/schemas/dataset_meta"
          group: "#/components/schemas/group_meta"
      oneOf:
        - $ref: "#/components/schemas/dataset_meta"
        - $ref: "#/components/schemas/group_meta"
    py_snippet:
      description: "python code snippet"
      type: string
    slice:
      description: "python-style slice"
      required: [start, stop, step]
      type: object
      properties:
        start:
          description: "first index of the slice"
          type: number
        stop:
          description: "one past the last index of the slice"
          type: number
        step:
          description: "step of the slice"
          type: number
